# Generated by Django 5.2.1 on 2025-05-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starodruk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul_transkrypcja', models.CharField(max_length=255)),
                ('tytul_transliteracja', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('miejsce_wydania', models.CharField(blank=True, max_length=255, null=True)),
                ('data_wydania', models.CharField(blank=True, max_length=100, null=True)),
                ('drukarnia', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('liczba_kart', models.CharField(blank=True, max_length=50, null=True)),
                ('liczba_arkuszy', models.CharField(blank=True, max_length=50, null=True)),
                ('jezyk', models.CharField(blank=True, max_length=100, null=True)),
                ('gatunek', models.CharField(blank=True, max_length=255, null=True)),
                ('adresat', models.CharField(blank=True, max_length=255, null=True)),
                ('okolicznosci_powstania', models.TextField(blank=True, null=True)),
                ('dodatkowe_informacje', models.TextField(blank=True, null=True)),
                ('sygnatury', models.TextField(blank=True, null=True)),
                ('link_do_wersji', models.URLField(blank=True, null=True)),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to='miniatury/')),
            ],
        ),
    ]
