# Generated by Django 5.2.1 on 2026-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jezyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Język',
                'verbose_name_plural': 'Języki',
                'ordering': ['nazwa'],
            },
        ),
        migrations.DeleteModel(
            name='Starodruk',
        ),
    ]
