# Generated by Django 5.2.1 on 2026-07-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_jezyk_delete_starodruk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formaty',
            },
        ),
        migrations.AlterModelOptions(
            name='jezyk',
            options={'verbose_name': 'Język', 'verbose_name_plural': 'Języki'},
        ),
    ]
