# Generated by Django 5.2.1 on 2026-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_format_alter_jezyk_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czcionka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Czcionka',
                'verbose_name_plural': 'Czcionki',
            },
        ),
    ]
