# Generated by Django 5.2.1 on 2026-07-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_czcionka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imiona', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('warianty', models.TextField(blank=True)),
                ('rok_urodzenia', models.PositiveIntegerField(blank=True, null=True)),
                ('rok_smierci', models.PositiveIntegerField(blank=True, null=True)),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'ordering': ['nazwisko', 'imiona'],
            },
        ),
    ]
