# Generated by Django 5.2.1 on 2026-07-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0005_osoba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Biblioteka',
                'verbose_name_plural': 'Biblioteki',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunki',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Instytucja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Instytucja',
                'verbose_name_plural': 'Instytucje',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Miejsce',
                'verbose_name_plural': 'Miejsca',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Motyw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Motyw',
                'verbose_name_plural': 'Motywy',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Temat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Temat',
                'verbose_name_plural': 'Tematy',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('czytaj_wiecej', models.TextField(blank=True)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['nazwa'],
            },
        ),
    ]
