# Generated by Django 5.2.1 on 2026-07-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0006_biblioteka_gatunek_instytucja_miejsce_motyw_temat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteka',
            options={'verbose_name': 'Biblioteka', 'verbose_name_plural': 'Biblioteki'},
        ),
        migrations.AlterModelOptions(
            name='gatunek',
            options={'verbose_name': 'Gatunek', 'verbose_name_plural': 'Gatunki'},
        ),
        migrations.AlterModelOptions(
            name='instytucja',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
        migrations.AlterModelOptions(
            name='miejsce',
            options={'verbose_name': 'Miejsce', 'verbose_name_plural': 'Miejsca'},
        ),
        migrations.AlterModelOptions(
            name='motyw',
            options={'verbose_name': 'Motyw', 'verbose_name_plural': 'Motywy'},
        ),
        migrations.AlterModelOptions(
            name='temat',
            options={'verbose_name': 'Temat', 'verbose_name_plural': 'Tematy'},
        ),
        migrations.AlterModelOptions(
            name='wydarzenie',
            options={'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
    ]
