# Generated by Django 5.2.1 on 2026-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0007_alter_biblioteka_options_alter_gatunek_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identyfikator', models.CharField(editable=False, help_text='Automatycznie nadawany sześciocyfrowy identyfikator BiDO.', max_length=6, unique=True)),
                ('tytul_skrocony', models.TextField()),
                ('tytul_pelny', models.TextField(blank=True)),
                ('rok_wydania', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rekord',
                'verbose_name_plural': 'Rekordy',
            },
        ),
    ]
