# Generated by Django 5.2.1 on 2026-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0008_rekord'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekord',
            name='kolacjonowanie',
            field=models.TextField(blank=True, verbose_name='Kolacjonowanie'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='liczba_arkuszy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Liczba arkuszy'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='liczba_kart',
            field=models.CharField(blank=True, max_length=100, verbose_name='Liczba kart'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='wersja_zdigitalizowana',
            field=models.URLField(blank=True, verbose_name='Wersja zdigitalizowana'),
        ),
        migrations.AlterField(
            model_name='rekord',
            name='rok_wydania',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Data wydania'),
        ),
        migrations.AlterField(
            model_name='rekord',
            name='tytul_pelny',
            field=models.TextField(blank=True, verbose_name='Tytuł pełny'),
        ),
        migrations.AlterField(
            model_name='rekord',
            name='tytul_skrocony',
            field=models.TextField(verbose_name='Tytuł skrócony'),
        ),
    ]
