# Generated by Django 5.2.1 on 2026-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0009_rekord_kolacjonowanie_rekord_liczba_arkuszy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekord',
            name='ozdobniki',
            field=models.TextField(blank=True, verbose_name='Ozdobniki'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='ryciny',
            field=models.TextField(blank=True, help_text='Pozostaw puste, jeśli druk nie zawiera rycin.', verbose_name='Ryciny'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='uwagi',
            field=models.TextField(blank=True, verbose_name='Uwagi'),
        ),
    ]
