# Generated by Django 5.2.1 on 2026-07-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0010_rekord_ozdobniki_rekord_ryciny_rekord_uwagi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacjaRekordu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('wariant', 'Wariant'), ('wznowienie', 'Wznowienie')], max_length=20)),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje', to='biblioteka.rekord')),
                ('rekord_powiazany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powiazane_z', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Relacja rekordu',
                'verbose_name_plural': 'Relacje rekordów',
            },
        ),
    ]
