# Generated by Django 5.2.1 on 2026-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0011_relacjarekordu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekord',
            name='bibliografie',
            field=models.TextField(blank=True, verbose_name='Bibliografie'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='literatura_przedmiotu',
            field=models.TextField(blank=True, verbose_name='Literatura przedmiotu, opracowania'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='pozostale_druki_powiazane',
            field=models.TextField(blank=True, help_text='Można wpisywać opisy bibliograficzne druków spoza bazy BiDO.', verbose_name='Pozostałe druki powiązane'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='streszczenie',
            field=models.TextField(blank=True, verbose_name='Streszczenie'),
        ),
    ]
