# Generated by Django 5.2.1 on 2026-07-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0012_rekord_bibliografie_rekord_literatura_przedmiotu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekord',
            name='miniatura',
            field=models.ImageField(blank=True, help_text='Miniatura wyświetlana na karcie rekordu i w wynikach wyszukiwania.', null=True, upload_to='miniatury/', verbose_name='Miniatura'),
        ),
    ]
