# Generated by Django 5.2.1 on 2026-07-02 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0013_rekord_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekord',
            name='czcionki',
            field=models.ManyToManyField(blank=True, to='biblioteka.czcionka', verbose_name='Czcionki'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.format', verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='jezyki',
            field=models.ManyToManyField(blank=True, to='biblioteka.jezyk', verbose_name='Języki'),
        ),
    ]
