# Generated by Django 5.2.1 on 2026-07-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0014_rekord_czcionki_rekord_format_rekord_jezyki'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacjaOsoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('autor', 'Autor'), ('drukarz', 'Drukarz'), ('adresat', 'Adresat dedykacji'), ('powiazana', 'Powiązana osoba')], max_length=20)),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.osoba')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_osob', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Relacja osoby',
                'verbose_name_plural': 'Relacje osób',
            },
        ),
    ]
