# Generated by Django 5.2.1 on 2026-07-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0015_relacjaosoby'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacjaMiejsca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('wydania', 'Miejsce wydania'), ('powiazane', 'Powiązane miejsce')], max_length=20)),
                ('miejsce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.miejsce')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_miejsc', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Relacja miejsca',
                'verbose_name_plural': 'Relacje miejsc',
            },
        ),
    ]
