# Generated by Django 5.2.1 on 2026-07-03 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0016_relacjamiejsca'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacjaGatunku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.gatunek')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_gatunkow', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Relacja gatunku',
                'verbose_name_plural': 'Relacje gatunków',
            },
        ),
        migrations.CreateModel(
            name='RelacjaInstytucji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instytucja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.instytucja')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_instytucji', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Relacja instytucji',
                'verbose_name_plural': 'Relacje instytucji',
            },
        ),
        migrations.CreateModel(
            name='RelacjaMotywu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motyw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.motyw')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_motywow', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Relacja motywu',
                'verbose_name_plural': 'Relacje motywów',
            },
        ),
        migrations.CreateModel(
            name='RelacjaTematu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_tematow', to='biblioteka.rekord')),
                ('temat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.temat')),
            ],
            options={
                'verbose_name': 'Relacja tematu',
                'verbose_name_plural': 'Relacje tematów',
            },
        ),
        migrations.CreateModel(
            name='RelacjaWydarzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacje_wydarzen', to='biblioteka.rekord')),
                ('wydarzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.wydarzenie')),
            ],
            options={
                'verbose_name': 'Relacja wydarzenia',
                'verbose_name_plural': 'Relacje wydarzeń',
            },
        ),
    ]
