# Generated by Django 5.2.1 on 2026-07-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0017_relacjagatunku_relacjainstytucji_relacjamotywu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('sygnatura', models.TextField(blank=True, verbose_name='Sygnatura')),
                ('katalog_biblioteczny', models.URLField(blank=True, verbose_name='Katalog biblioteczny')),
                ('oprawa', models.TextField(blank=True, verbose_name='Oprawa')),
                ('marginalia', models.TextField(blank=True, help_text='Pozostaw puste, jeśli egzemplarz nie zawiera marginaliów ani śladów lektury.', verbose_name='Marginalia, ślady lektury')),
                ('biblioteka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteka.biblioteka', verbose_name='Biblioteka')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egzemplarze', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Egzemplarz',
                'verbose_name_plural': 'Egzemplarze',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
