# Generated by Django 5.2.1 on 2026-07-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0018_egzemplarz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpracowanieRekordu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(blank=True, max_length=200, verbose_name='Imię i nazwisko')),
                ('sposob_dodania', models.CharField(choices=[('auto', 'Automatycznie'), ('recznie', 'Ręcznie')], default='auto', max_length=20)),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1)),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opracowanie', to='biblioteka.rekord')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Opracowanie rekordu',
                'verbose_name_plural': 'Opracowanie rekordu',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
