# Generated by Django 5.2.1 on 2026-07-03 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0019_opracowanierekordu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekord',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data dodania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rekord',
            name='data_ostatniej_modyfikacji',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ostatniej modyfikacji'),
        ),
        migrations.AddField(
            model_name='rekord',
            name='status_opracowania',
            field=models.CharField(choices=[('do_opracowania', 'Do opracowania'), ('czesciowo_opracowany', 'Częściowo opracowany'), ('opracowany', 'Opracowany')], default='do', max_length=30, verbose_name='Status opracowania'),
        ),
    ]
