# Generated by Django 5.2.1 on 2026-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0020_rekord_data_dodania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egzemplarz',
            name='proweniencja',
            field=models.TextField(blank=True, verbose_name='Proweniencja'),
        ),
        migrations.AlterField(
            model_name='rekord',
            name='status_opracowania',
            field=models.CharField(choices=[('do_opracowania', 'Do opracowania'), ('czesciowo_opracowany', 'Częściowo opracowany'), ('opracowany', 'Opracowany')], default='do_opracowania', max_length=30, verbose_name='Status opracowania'),
        ),
    ]
