# Generated by Django 5.2.1 on 2026-07-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0021_egzemplarz_proweniencja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opracowanierekordu',
            options={'ordering': ['kolejnosc', 'id'], 'verbose_name': 'Autor opracowania', 'verbose_name_plural': 'Autorzy opracowania'},
        ),
        migrations.RemoveField(
            model_name='rekord',
            name='wersja_zdigitalizowana',
        ),
        migrations.AlterField(
            model_name='opracowanierekordu',
            name='kolejnosc',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność'),
        ),
        migrations.CreateModel(
            name='WersjaZdigitalizowana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wersje_zdigitalizowane', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Wersja zdigitalizowana',
                'verbose_name_plural': 'Wersje zdigitalizowane',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
