# Generated by Django 5.2.1 on 2026-07-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0022_alter_opracowanierekordu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='rekord',
            name='tagi',
            field=models.ManyToManyField(blank=True, to='biblioteka.tag', verbose_name='Tagi'),
        ),
    ]
