# Generated by Django 5.2.1 on 2026-07-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0023_tag_rekord_tagi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zalacznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ozdobniki', 'Ozdobniki'), ('ryciny', 'Ryciny'), ('uwagi', 'Uwagi'), ('literatura_przedmiotu', 'Literatura przedmiotu'), ('marginalia', 'Marginalia')], max_length=30)),
                ('plik', models.FileField(upload_to='zalaczniki/', verbose_name='Plik')),
                ('opis', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('egzemplarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zalaczniki', to='biblioteka.egzemplarz')),
                ('rekord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zalaczniki', to='biblioteka.rekord')),
            ],
            options={
                'verbose_name': 'Załącznik',
                'verbose_name_plural': 'Załączniki',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
