# Generated by Django 5.2.1 on 2026-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0024_zalacznik'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalacznik',
            name='nazwa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa wyświetlana'),
        ),
    ]
