# Generated by Django 5.2.1 on 2026-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0025_zalacznik_nazwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zalacznik',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='zalacznik',
            name='nazwa_wyswietlana',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nazwa wyświetlana'),
        ),
    ]
