# Generated by Django 5.2.1 on 2026-07-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0026_remove_zalacznik_nazwa_zalacznik_nazwa_wyswietlana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='warianty',
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='gatunek',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='gatunek',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='gatunek',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='instytucja',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='instytucja',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='instytucja',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='miejsce',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='miejsce',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='miejsce',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='motyw',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='motyw',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='motyw',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='kwalifikator',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kwalifikator'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='temat',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='temat',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='temat',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='ilustracja',
            field=models.ImageField(blank=True, null=True, upload_to='obiekty/', verbose_name='Ilustracja'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='podpis_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Podpis ilustracji'),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='zrodlo_ilustracji',
            field=models.CharField(blank=True, max_length=255, verbose_name='Źródło ilustracji'),
        ),
        migrations.CreateModel(
            name='WariantNazwyOsoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.osoba')),
            ],
            options={
                'verbose_name': 'Wariant nazwy osoby',
                'verbose_name_plural': 'Warianty nazw osób',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
