# Generated by Django 5.2.1 on 2026-07-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0027_remove_osoba_warianty_biblioteka_ilustracja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WariantNazwyBiblioteki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('biblioteka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.biblioteka')),
            ],
            options={
                'verbose_name': 'Wariant nazwy biblioteki',
                'verbose_name_plural': 'Warianty nazw bibliotek',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WariantNazwyGatunku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('gatunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.gatunek')),
            ],
            options={
                'verbose_name': 'Wariant nazwy gatunku',
                'verbose_name_plural': 'Warianty nazw gatunków',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WariantNazwyInstytucji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('instytucja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.instytucja')),
            ],
            options={
                'verbose_name': 'Wariant nazwy instytucji',
                'verbose_name_plural': 'Warianty nazw instytucji',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WariantNazwyMiejsca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('miejsce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.miejsce')),
            ],
            options={
                'verbose_name': 'Wariant nazwy miejsca',
                'verbose_name_plural': 'Warianty nazw miejsc',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WariantNazwyMotywu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('motyw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.motyw')),
            ],
            options={
                'verbose_name': 'Wariant nazwy motywu',
                'verbose_name_plural': 'Warianty nazw motywów',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WariantNazwyTematu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('temat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.temat')),
            ],
            options={
                'verbose_name': 'Wariant nazwy tematu',
                'verbose_name_plural': 'Warianty nazw tematów',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WariantNazwyWydarzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Wariant nazwy')),
                ('kolejnosc', models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność')),
                ('wydarzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warianty_nazw', to='biblioteka.wydarzenie')),
            ],
            options={
                'verbose_name': 'Wariant nazwy wydarzenia',
                'verbose_name_plural': 'Warianty nazw wydarzeń',
                'ordering': ['kolejnosc', 'id'],
            },
        ),
    ]
