# Generated by Django 5.2.1 on 2026-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0028_wariantnazwybiblioteki_wariantnazwygatunku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zalacznik',
            name='typ',
        ),
        migrations.AddField(
            model_name='zalacznik',
            name='sekcja',
            field=models.CharField(choices=[('ozdobniki', 'Ozdobniki'), ('ryciny', 'Ryciny'), ('uwagi', 'Uwagi'), ('literatura_przedmiotu', 'Literatura przedmiotu'), ('marginalia', 'Marginalia'), ('inne', 'Inne')], default='inne', max_length=30, verbose_name='Sekcja'),
            preserve_default=False,
        ),
    ]
