# Generated by Django 5.2.1 on 2026-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0029_remove_zalacznik_typ_zalacznik_sekcja'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacjarekordu',
            name='opis',
            field=models.TextField(blank=True, verbose_name='Opis bibliograficzny'),
        ),
        migrations.AlterField(
            model_name='zalacznik',
            name='sekcja',
            field=models.CharField(choices=[('ozdobniki', 'Ozdobniki'), ('ryciny', 'Ryciny'), ('uwagi', 'Uwagi'), ('literatura_przedmiotu', 'Literatura przedmiotu'), ('marginalia', 'Marginalia'), ('inne', 'Inne')], default='inne', max_length=30, verbose_name='Sekcja'),
        ),
    ]
