# Generated by Django 5.2.1 on 2026-07-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0030_relacjarekordu_opis_alter_zalacznik_sekcja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacjarekordu',
            name='rekord_powiazany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='powiazane_z', to='biblioteka.rekord'),
        ),
    ]
