# Generated by Django 5.2.1 on 2026-07-15 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0031_alter_relacjarekordu_rekord_powiazany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDanych',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateTimeField(auto_now_add=True)),
                ('data_zakonczenia', models.DateTimeField(blank=True, null=True)),
                ('plik', models.FileField(upload_to='importy/')),
                ('liczba_rekordow', models.PositiveIntegerField(default=0)),
                ('liczba_egzemplarzy', models.PositiveIntegerField(default=0)),
                ('liczba_zalacznikow', models.PositiveIntegerField(default=0)),
                ('czas_trwania', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('w_trakcie', 'W trakcie'), ('zakonczony', 'Zakończony'), ('blad', 'Błąd')], default='w_trakcie', max_length=20)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesja importu danych',
                'verbose_name_plural': 'Sesje importu danych',
            },
        ),
    ]
