# Generated by Django 5.2.1 on 2026-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0032_importdanych'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdanych',
            name='raport',
            field=models.FileField(blank=True, null=True, upload_to='import_reports/'),
        ),
    ]
