# Generated by Django 5.2.1 on 2026-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0033_importdanych_raport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdanych',
            name='status',
            field=models.CharField(choices=[('w_trakcie', 'W trakcie'), ('gotowy', 'Gotowy do importu'), ('zakonczony', 'Zakończony'), ('blad', 'Błąd')], default='w_trakcie', max_length=20),
        ),
    ]
