# Generated by Django 5.2.1 on 2026-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0034_alter_importdanych_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdanych',
            name='statystyki_obiektow',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
